_wandb:
    value:
        cli_version: 0.25.0
        e:
            ctwrab5f8e1no6utl9rvdkasutu67zkm:
                codePath: src\train1.py
                codePathLocal: train1.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "493026799616"
                        used: "207232401408"
                email: ma24m016@smail.iitm.ac.in
                executable: C:\Users\moni9\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 2147189c7e3b7a8b7affcc81af74bda20ebab94d
                    remote: https://github.com/monika763/da6401_assignment_1
                host: LAPTOP-UQ1P4DOI
                memory:
                    total: "16847933440"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\moni9\OneDrive\Desktop\DL\da6401_assignment_1\src\train1.py
                python: CPython 3.13.3
                root: C:\Users\moni9\OneDrive\Desktop\DL\da6401_assignment_1\src
                startedAt: "2026-03-04T09:50:35.829965Z"
                writerId: ctwrab5f8e1no6utl9rvdkasutu67zkm
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 16
            "4": 3.13.3
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
dataset:
    value: mnist
logging:
    value:
        project_name: mnist-fnn
        wandb_mode: online
model:
    value:
        activation: relu
        hidden_layers: 3
        initialization: xavier
        loss: cross_entropy
        neurons: 128
sweep:
    value:
        method: random
        metric:
            goal: maximize
            name: val_accuracy
        parameters:
            activation:
                values:
                    - relu
                    - sigmoid
                    - tanh
            batch_size:
                values:
                    - 32
                    - 64
            hidden_layers:
                values:
                    - 2
                    - 3
            initialization:
                values:
                    - xavier
                    - zeros
            learning_rate:
                values:
                    - 0.001
                    - 0.01
                    - 0.1
            loss:
                values:
                    - cross_entropy
                    - mse
            neurons:
                values:
                    - 64
                    - 128
            optimizer:
                values:
                    - sgd
                    - momentum
                    - nesterov
                    - rmsprop
                    - adam
                    - nadam
training:
    value:
        batch_size: 64
        epochs: 10
        learning_rate: 0.001
        optimizer: adam
