wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
initialization_method:
  value: normal
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 2
num_neurons:
  value: '64'
optimizer:
  value: nadam
random_seed:
  value: 123
val_ratio:
  value: 0.1
weight_decay:
  value: 0
