wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
initialization_method:
  value: normal
learning_rate:
  value: 0.0005
num_hidden_layers:
  value: 4
num_neurons:
  value: '128'
optimizer:
  value: sgd
random_seed:
  value: 7
val_ratio:
  value: 0.1
weight_decay:
  value: 0
