wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
initialization_method:
  value: he
learning_rate:
  value: 0.003
num_hidden_layers:
  value: 2
num_neurons:
  value: '64'
optimizer:
  value: rmsprop
random_seed:
  value: 7
val_ratio:
  value: 0.1
weight_decay:
  value: 0.0005
