_wandb:
    value:
        cli_version: 0.25.0
        e:
            kv5baz544i86xgfabv40n6c3rlpcg0bc:
                args:
                    - --use_wandb
                    - --wandb_project
                    - da6401-assignment1
                codePath: src\train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "493026799616"
                        used: "205760573440"
                email: ma24m016@smail.iitm.ac.in
                executable: C:\Users\moni9\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 2147189c7e3b7a8b7affcc81af74bda20ebab94d
                    remote: https://github.com/monika763/da6401_assignment_1
                host: LAPTOP-UQ1P4DOI
                memory:
                    total: "16847933440"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\moni9\OneDrive\Desktop\DL\da6401_assignment_1\src\train.py
                python: CPython 3.13.3
                root: C:\Users\moni9\OneDrive\Desktop\DL\da6401_assignment_1\src
                startedAt: "2026-02-25T06:23:10.999450Z"
                writerId: kv5baz544i86xgfabv40n6c3rlpcg0bc
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
                - 17
            "4": 3.13.3
            "5": 0.25.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: fashion_mnist
epochs:
    value: 10
eval_batch_size:
    value: 256
hidden_dims:
    value: 128,64
learning_rate:
    value: 0.001
model_path:
    value: models\best_model.npz
momentum_beta:
    value: 0.9
optimizer:
    value: adam
seed:
    value: 42
sweep:
    value: false
sweep_count:
    value: 10
use_wandb:
    value: true
validation_split:
    value: 0.1
wandb_project:
    value: da6401-assignment1
weight_decay:
    value: 0
weight_init:
    value: xavier
