wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
initialization_method:
  value: normal
learning_rate:
  value: 0.003
num_hidden_layers:
  value: 3
num_neurons:
  value: '512'
optimizer:
  value: nesterov
random_seed:
  value: 42
val_ratio:
  value: 0.1
weight_decay:
  value: 0.001
